#eureka配置
eureka:
  instance:
    instance-id: ${spring.application.name}        #定义微服务的名称
    prefer-ip-address: true        #是否显示ip和端口
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/

#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.example.pojo
  mapper-locations: classpath:/mappers/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true  #自动开启驼峰规则映射


# dev环境时端口号为10002
---
server:
  port: 10002

spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_test?characterEncoding=utf8
    username: root
    password: root
  #eureka服务的名称
  application:
    name: provider-config


# dev环境时端口号为10003
---
server:
  port: 10003

spring:
  profiles: prod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_test?characterEncoding=utf8
    username: root
    password: root
  #eureka服务的名称
  application:
    name: provider-config

