
# dev环境时端口号为10002
---
server:
  port: 10002

spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_test?characterEncoding=utf8
    username: root
    password: root
  #eureka服务的名称
  application:
    name: provider-config


# prod环境时端口号为10003
---
server:
  port: 10003

spring:
  profiles: prod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_test?characterEncoding=utf8
    username: root
    password: root
  #eureka服务的名称
  application:
    name: provider-config

